### ISSUE TITLE
Easier instruction for install chromedriver on Mac.

### ISSUE THREAD

**Issue by johnkchiu** [paypal/nemo-docs#2]
For Mac, there's a brew formula (http://brewformulas.org/Chromedriver), which makes installin much easier.  It'll put binary in `/usr/local/bin/chromedriver`.  To install, it's simply `brew install chromedriver`.

**Comment by nikulkarni** [comment]
@johnkchiu Would you mind adding that here- https://github.com/paypal/nemo-docs/blob/master/driver-setup.md#getting-chromedriver

Thanks!

**Comment by grawk** [comment]
closing
